### ISSUE TITLE
Missing signing logic?

### ISSUE THREAD

**Issue by igrigorik** [hmcfletch/encrypted-cookies#2]
Readme mentions that cookies will be encrypted and signed, but a quick inspection of the code shows that the gem is calling `encrypt` and `decrypt` without the signing part? 

Sign+Encrypt methods in MessageEncryptor: https://github.com/rails/rails/blob/master/activesupport/lib/active_support/message_encryptor.rb#L50-60

(the tests need to be updated as well to reflect this)

**Comment by meder** [comment]
invalid signature test should trigger InvalidSignature exception

**Comment by hmcfletch** [comment]
You guys are right, sorry about that. I'll take care of it when I get home tonight. Thanks for the catch.

**Comment by hmcfletch** [comment]
Hey guys, I have been looking into this. There are a number of changes coming down the pipe for MessageEncryptor and MessageVerifier. It's going to be a bit of a bigger deal to get all this working smoothly with all of the different versions of Rails 3. I want this to just work regardless of which minor release you have, so I'll be working on this over Thanksgiving. Thanks for your patience.

@meder take a look at the SignedCookieJar (https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/middleware/cookies.rb#L289-295), it returns nil on an invalid signature. I was just following that convention.

**Comment by igrigorik** [comment]
Les, no hurry, and thanks for looking into this! FWIW, getting it to work with latest and greatest is what we're after atm. :)

**Comment by hmcfletch** [comment]
Quick update. I had some fights with my development environment trying to get Rails master up and running. So no new code. Getting the correct functionality in and released would be pretty trivial, just need to swap out the correct function call.  The problem is that this update will be a breaking change that will invalidate all encrypted cookies that people are currently using. So I am taking this opportunity to update the tests and push out a full 1.0 release. There will also be some new tests, especially for people running rails 3.2. With 3.2 I should be able to test the cookie value for correctness through the entire process and verify all the different parts are right. I don't people to have to worry about this gem functioning correctly.

Also, I haven't tested this yet, but looking at some of the commits to ActiveSupport::MessageEncryptor and MessageVerifier, I have a suspicion that some of the changes will prevent messages encrypted and signed with 3.1 to no be decrypted and verified under 3.2. I'll be looking into that as well.

Ok.. so not so quick. Hopefully in the next few days... fingers crossed.

**Comment by igrigorik** [comment]
That sounds great, thanks Les! Looking forward to playing with 1.0.

**Comment by hmcfletch** [comment]
Unit tests are all passing, but I need to test on some actual rails projects before I feel good about pushing an updated gem out.

**Comment by hmcfletch** [comment]
New gem released. Enjoy.

**Comment by igrigorik** [comment]
Nice. Thanks!
